services:
  postgres:
    image: postgres:15
    container_name: scrapper-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/

  redis:
    image: redis:7-alpine
    container_name: scrapper-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - scrapper-net

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: scrapper-redis-insight
    ports:
      - "8001:5540"
    volumes:
      - redisinsight-data:/db
    depends_on:
      - redis
    networks:
      - scrapper-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: scrapper-zookeeper
    hostname: zookeeper
    networks:
      - scrapper-net
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data

  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: scrapper-kafka-1
    hostname: kafka-1
    networks:
      - scrapper-net
    depends_on:
      - zookeeper
    ports:
      - "19092:19092"
    environment:

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:19092,INTERNAL://kafka-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_MIN_IN_SYNC_REPLICAS: 2

    volumes:
      - kafka1-data:/var/lib/kafka/data

  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: scrapper-kafka-2
    hostname: kafka-2
    networks:
      - scrapper-net
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:29092,INTERNAL://kafka-2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_MIN_IN_SYNC_REPLICAS: 2
    volumes:
      - kafka2-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: scrapper-kafka-ui
    networks:
      - scrapper-net
    ports:
      - "8084:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./kui/config.yml:/etc/kafkaui/config.yaml

volumes:
  postgres-data:
  redis-data:
  zookeeper-data:
  kafka1-data:
  kafka2-data:
  redisinsight-data:

networks:
  scrapper-net:
    driver: bridge
